### ISSUE TITLE
`TF2Util_GetPlayerMaxHealth` does not discount overheal correctly.

### ISSUE THREAD

**Issue by sniggyfigbat** [nosoop/SM-TFUtils#1]
`TF2Util_GetPlayerMaxHealth` doesn't handle overheal correctly, no matter what `bIgnoreOverheal` is set to. Fairly confident this isn't intended behaviour, as [`projectile_heal_on_teammate_contact.sp`](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/blob/master/scripting/projectile_heal_on_teammate_contact.sp) in the Custom Attribute Starter Pack explicitly uses base health to calculate a separate max overheal proportion.

This code:

```
	int iMaxHP = TF2Util_GetPlayerMaxHealth(attacker, false, false);
	PrintToServer("Max HP (bIgnoreOverheal = false):");
	char bffr5[16];
	IntToString(iMaxHP, bffr5, 16);
	PrintToServer(bffr5);
	
	iMaxHP = TF2Util_GetPlayerMaxHealth(attacker, false, true);
	PrintToServer("Max HP (bIgnoreOverheal = true):");
	char bffr6[16];
	IntToString(iMaxHP, bffr6, 16);
	PrintToServer(bffr6);
```

Produces this output in console:

![image](https://user-images.githubusercontent.com/3359069/127342609-719d9d0f-2d8a-4404-b3b4-5787b4ac7dd4.png)

*(Note: This is on Demoman, so it is at least calculating max HP with overheal correctly.)*

**Comment by nosoop** [comment]
I never actually looked into what it was doing, whoops.

So what the underlying call actually does is check buffed health &mdash; the amount that mediguns can overheal to, basically.  `bIgnoreOverheal` ignores the current health for the purpose of overheal decay.  Giving yourself overheal through something like [Set Health](https://forums.alliedmods.net/showthread.php?p=650481) (I think that's the one) will show the unclamped health when `bIgnoreOverheal` is set to false.

Looks like I'll have to deprecate and rename the function in this case and add `TF2_GetEntityMaxHealth` to get true maxhealth (it's available as a virtual call so that wouldn't be too much of a hassle).  I'll look into testing it when I have the time.

**Comment by nosoop** [comment]
This fell by the wayside, sorry; I blame Github's watch functionality for this.

I'll make a note to test and push the changes for this out within the next day:

- `TF2Util_GetPlayerMaxHealth` will be deprecated, and usage of it will report a warning in the future.
- `TF2Util_GetEntityMaxHealth` should return the player's maximum health without overheal, and is able to report maximum health on other entities.
- `TF2Util_GetPlayerMaxHealthBoost` will return the maximum allowed overheal for a player (which is the behavior of `TF2Util_GetPlayerMaxHealth`, just renamed to avoid confusion)

**Comment by nosoop** [comment]
Sorry for the delay; just got around to testing the changes.  Release 0.13.0 is now up with the changes outlined above.
